name: Ejecutar prueba.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v3

      - name: Ejecutar prueba.js
        run: node prueba.js

        
        